import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#121212', padding: 20 },
  mealsList: {
    flex: 1,
  },
  mealsListContent: {
    paddingBottom: 120,
  },
  
  // Date Picker
  dateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  dateArrow: {
    padding: 10,
  },
  dateDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1E1E',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
  },
  dateText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  
  // Summary Card
  summaryCard: {
    backgroundColor: '#2A1D3D',
    padding: 25,
    borderRadius: 20,
    alignItems: 'center',
    marginBottom: 25,
    borderWidth: 1,
    borderColor: '#BB86FC55',
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 10,
  },
  summaryActions: {
    flexDirection: 'row',
    gap: 8,
  },
  summaryTitle: { color: '#BB86FC', fontSize: 14, fontWeight: 'bold' },
  copyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1E1E',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  copyBtnText: {
    color: '#BB86FC',
    fontSize: 12,
    marginLeft: 5,
  },
  calorieText: { color: 'white', fontSize: 42, fontWeight: '200' },
  macroRow: { flexDirection: 'row', marginTop: 20, gap: 30 },
  macroItem: { alignItems: 'center' },
  macroValue: { color: 'white', fontSize: 18, fontWeight: 'bold' },
  macroLabel: { color: '#888', fontSize: 12, marginTop: 2 },

  quickAddRow: {
    marginBottom: 16,
  },
  quickAddRowContent: {
    gap: 10,
    paddingRight: 20,
  },
  quickAddCard: {
    width: 150,
    backgroundColor: '#1E1E1E',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#2D2D2D',
  },
  quickAddCardPrimary: {
    borderColor: '#BB86FC55',
    backgroundColor: '#191427',
  },
  quickAddTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 10,
  },
  quickAddMeta: {
    color: '#888',
    fontSize: 11,
    marginTop: 4,
    lineHeight: 15,
  },
  offInfoCard: {
    backgroundColor: '#171A23',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2A3042',
  },
  offInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  offInfoTitle: {
    color: '#D8DDFF',
    fontWeight: 'bold',
  },
  offInfoText: {
    color: '#99A1C4',
    fontSize: 12,
    lineHeight: 17,
  },
  goalsCard: {
    backgroundColor: '#1A1B1E',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2C2D31',
  },
  goalsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  goalsTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  goalsSubtitle: {
    color: '#888',
    fontSize: 12,
  },
  goalRow: {
    marginTop: 10,
  },
  goalRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
    gap: 12,
  },
  goalLabelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  goalLabel: {
    color: '#CCC',
    fontSize: 13,
  },
  goalStatusBadge: {
    backgroundColor: '#2A2D31',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  goalStatusBadgeGood: {
    backgroundColor: '#18362F',
  },
  goalStatusBadgeHigh: {
    backgroundColor: '#3C2328',
  },
  goalStatusText: {
    color: '#B8C0C7',
    fontSize: 10,
    fontWeight: '700',
  },
  goalStatusTextGood: {
    color: '#5EEAD4',
  },
  goalStatusTextHigh: {
    color: '#FF9EA8',
  },
  goalValue: {
    color: '#EEE',
    fontSize: 12,
    fontWeight: '600',
  },
  goalTrack: {
    height: 9,
    borderRadius: 999,
    backgroundColor: '#101114',
    overflow: 'hidden',
  },
  goalFill: {
    height: '100%',
    borderRadius: 999,
  },
  insightsCard: {
    backgroundColor: '#151A20',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#25303B',
  },
  insightsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  insightsTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  insightsSubtitle: {
    color: '#8EA2B6',
    fontSize: 12,
  },
  insightsLead: {
    color: '#D8E3EE',
    fontSize: 13,
    lineHeight: 19,
  },
  weeklyChartCard: {
    backgroundColor: '#14181F',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#27313E',
  },
  weeklyChartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  weeklyChartTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  weeklyChartSubtitle: {
    color: '#8EA2B6',
    fontSize: 12,
    marginTop: 4,
  },
  weeklyChartRange: {
    color: '#99A1C4',
    fontSize: 12,
    fontWeight: '700',
  },
  weeklyMetricSection: {
    marginTop: 12,
  },
  weeklyMetricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  weeklyMetricLabel: {
    color: '#E7EEF5',
    fontSize: 13,
    fontWeight: '700',
  },
  weeklyMetricMeta: {
    color: '#8EA2B6',
    fontSize: 12,
  },
  weeklyBarsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
  },
  weeklyBarItem: {
    flex: 1,
    alignItems: 'center',
  },
  weeklyBarTrack: {
    width: '100%',
    height: 64,
    borderRadius: 12,
    backgroundColor: '#0D1116',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    padding: 4,
  },
  weeklyBarFill: {
    width: '100%',
    borderRadius: 8,
    minHeight: 0,
  },
  weeklyBarValue: {
    color: '#CCD8E3',
    fontSize: 10,
    marginTop: 6,
  },
  weeklyBarLabel: {
    color: '#7F8FA2',
    fontSize: 10,
    marginTop: 3,
  },
  periodSummaryCard: {
    backgroundColor: '#171A23',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2A3042',
  },
  periodSummaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  periodSummaryTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  periodSummarySubtitle: {
    color: '#99A1C4',
    fontSize: 12,
    marginTop: 4,
  },
  periodConsistencyBadge: {
    backgroundColor: '#20273A',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  periodConsistencyText: {
    color: '#D8DDFF',
    fontSize: 11,
    fontWeight: '700',
  },
  periodStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  periodStatCard: {
    flex: 1,
    backgroundColor: '#1E2331',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#2C3450',
  },
  periodStatValue: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  periodStatLabel: {
    color: '#99A1C4',
    fontSize: 12,
    marginTop: 6,
  },
  periodGoalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  periodGoalItem: {
    width: '48%',
    backgroundColor: '#1E2331',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#2C3450',
  },
  periodGoalLabel: {
    color: '#D8DDFF',
    fontSize: 12,
    fontWeight: '700',
  },
  periodGoalValue: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 8,
  },
  periodGoalMeta: {
    color: '#8EA2B6',
    fontSize: 11,
    marginTop: 5,
  },
  insightStatRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  insightStatCard: {
    flex: 1,
    backgroundColor: '#1C232B',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#283340',
  },
  insightStatLabel: {
    color: '#8EA2B6',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  insightStatValue: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
    marginTop: 8,
  },
  insightStatMeta: {
    color: '#9AA8B6',
    fontSize: 12,
    marginTop: 6,
  },
  sourceBreakdownRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
    flexWrap: 'wrap',
  },
  sourceBreakdownChip: {
    backgroundColor: '#1C232B',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#283340',
  },
  sourceBreakdownLabel: {
    color: '#F4F7FA',
    fontWeight: '700',
    fontSize: 12,
  },
  sourceBreakdownMeta: {
    color: '#8EA2B6',
    fontSize: 11,
    marginTop: 2,
  },
  sourceBreakdownEmpty: {
    backgroundColor: '#1C232B',
    borderRadius: 12,
    padding: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: '#283340',
  },
  sourceBreakdownEmptyText: {
    color: '#8EA2B6',
    fontSize: 12,
  },
  macroSplitSection: {
    marginTop: 16,
  },
  macroSplitTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  macroSplitRow: {
    marginTop: 10,
  },
  macroSplitHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  macroSplitLabel: {
    color: '#CCD8E3',
    fontSize: 12,
  },
  macroSplitMeta: {
    color: '#8EA2B6',
    fontSize: 12,
  },
  macroSplitTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#0D1116',
    overflow: 'hidden',
  },
  macroSplitFill: {
    height: '100%',
    borderRadius: 999,
  },
  recentMealsCard: {
    marginBottom: 16,
  },
  recentMealsTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  recentMealsRail: {
    gap: 10,
    paddingRight: 20,
  },
  recentMealChip: {
    width: 180,
    backgroundColor: '#1E1E1E',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#2D2D2D',
  },
  templateChip: {
    width: 190,
    backgroundColor: '#1E1E1E',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#2D2D2D',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  templateChipBody: {
    flex: 1,
  },
  templateDeleteBtn: {
    padding: 4,
  },
  recentMealChipName: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  recentMealChipMeta: {
    color: '#888',
    fontSize: 11,
    marginTop: 5,
  },
  
  // Meal Tabs
  mealTypeTabs: {
    maxHeight: 50,
    height: 50,
    minHeight: 50,
    flexShrink: 0,
    marginBottom: 15,
  },
  mealTypeTabsContent: {
    paddingRight: 20,
    gap: 8,
  },
  mealTypeTab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1E1E',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    gap: 6,
  },
  mealTypeTabActive: {
    backgroundColor: '#BB86FC',
  },
  mealTypeTabText: {
    color: '#888',
    fontSize: 13,
    fontWeight: '500',
  },
  mealTypeTabTextActive: {
    color: '#fff',
  },
  mealTypeCalories: {
    color: '#BB86FC',
    fontSize: 11,
    fontWeight: 'bold',
    backgroundColor: '#1E1E1E',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  
  // Section
  sectionTitle: { color: 'white', fontSize: 18, fontWeight: 'bold', marginBottom: 15, marginTop: 10 },
  
  // Meal Card
  mealCard: {
    backgroundColor: '#1E1E1E',
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  mealCardMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  mealTypeIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#2A1D3D',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  mealInfo: { flex: 1 },
  mealHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  mealBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-end',
  },
  mealName: { color: 'white', fontSize: 15, fontWeight: 'bold' },
  mealBrand: { color: '#888', fontSize: 11 },
  mealMacros: { color: '#666', fontSize: 11, marginTop: 4 },
  sourcePill: {
    color: '#D5C7F6',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: '#2A1D3D',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  sourcePillVerified: {
    color: '#5EEAD4',
    backgroundColor: '#163433',
  },
  verifiedPill: {
    color: '#5EEAD4',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: '#163433',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  customPill: {
    color: '#FFCC80',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: '#332411',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  deleteBtn: {
    minWidth: 74,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  deleteBtnText: {
    color: '#CF6679',
    fontSize: 11,
    fontWeight: '700',
  },
  mealActionsHint: {
    backgroundColor: '#171A23',
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#282D3E',
  },
  mealActionsHintText: {
    color: '#99A1C4',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  
  emptyContainer: { alignItems: 'center', marginTop: 40 },
  emptyText: { color: '#444', textAlign: 'center' },
  copyFromPastBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
    backgroundColor: '#1E1E1E',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
  },
  copyFromPastText: {
    color: '#BB86FC',
    marginLeft: 8,
    fontSize: 14,
  },
  
  // Day selector modal
  dayItem: {
    backgroundColor: '#1E1E1E',
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dayItemActive: {
    borderWidth: 1,
    borderColor: '#BB86FC',
    backgroundColor: '#2A1D3D',
  },
  dayItemDate: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  dayItemCount: {
    color: '#888',
    fontSize: 12,
    marginTop: 2,
  },
  dayItemMacros: {
    color: '#BB86FC',
    fontSize: 14,
    fontWeight: 'bold',
  },
  
  // Kopyalama modal
  copyInfo: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  copyDayItem: {
    backgroundColor: '#1E1E1E',
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  copyDayMeals: {
    color: '#666',
    fontSize: 11,
    marginTop: 5,
    fontStyle: 'italic',
  },
  
  // FAB
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    backgroundColor: '#BB86FC',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#BB86FC',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  
  // Takvim
  todayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A1D3D',
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
  },
  todayBtnText: {
    color: '#BB86FC',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-start',
  },
  calendarDay: {
    width: '18%',
    aspectRatio: 0.9,
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarDaySelected: {
    backgroundColor: '#BB86FC',
  },
  monthNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 12,
  },
  monthNavBtn: {
    padding: 8,
  },
  monthNavTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
    textTransform: 'capitalize',
  },
  calendarDayHasMeals: {
    borderWidth: 1,
    borderColor: '#BB86FC55',
  },
  calendarDayToday: {
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  calendarDayNumToday: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  calendarMonth: {
    color: '#BB86FC',
    fontSize: 9,
    fontWeight: 'bold',
    position: 'absolute',
    top: 4,
    left: 6,
  },
  calendarDayNum: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  calendarDayNumSelected: {
    color: '#fff',
  },
  calendarDayName: {
    color: '#666',
    fontSize: 10,
  },
  calendarDayCalories: {
    color: '#BB86FC',
    fontSize: 9,
    marginTop: 2,
  },
  
  // Modal
  modalContainer: { flex: 1, backgroundColor: '#121212', padding: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { color: 'white', fontSize: 22, fontWeight: 'bold' },
  
  // Modal sekmeleri (Ara / Favoriler)
  modalTabs: {
    flexDirection: 'row',
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    padding: 4,
    marginBottom: 15,
  },
  modalTabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    gap: 6,
  },
  modalTabBtnActive: {
    backgroundColor: '#BB86FC',
  },
  modalTabText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '500',
  },
  modalTabTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  
  // Meal type selector (inside modal)
  mealTypeSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 8,
  },
  mealTypeSelectorBtn: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#1E1E1E',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 12,
    gap: 4,
  },
  mealTypeSelectorBtnActive: {
    backgroundColor: '#BB86FC',
  },
  mealTypeSelectorText: {
    color: '#888',
    fontSize: 11,
  },
  mealTypeSelectorTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  
  // Arama
  searchRow: { flexDirection: 'row', marginBottom: 10 },
  searchInput: {
    flex: 1,
    backgroundColor: '#1E1E1E',
    color: 'white',
    padding: 15,
    borderRadius: 12,
    fontSize: 16,
    marginRight: 10,
  },
  searchBtn: {
    backgroundColor: '#BB86FC',
    padding: 15,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchHelperText: {
    color: '#666',
    fontSize: 12,
    marginBottom: 12,
  },
  quickAccessRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  quickAccessCard: {
    flex: 1,
    backgroundColor: '#1E1E1E',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#2E2E2E',
  },
  quickAccessCardAccent: {
    backgroundColor: '#26171C',
    borderColor: '#CF667944',
  },
  resultsContainer: {
    flex: 1,
    minHeight: 260,
  },
  resultsList: {
    flex: 1,
  },
  resultsListContent: {
    paddingBottom: 24,
  },
  quickAccessTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 8,
  },
  quickAccessMeta: {
    color: '#888',
    fontSize: 11,
    marginTop: 4,
    lineHeight: 15,
  },
  barcodeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#161621',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#2A2D41',
    marginBottom: 14,
  },
  barcodeCardActive: {
    backgroundColor: '#BB86FC',
    borderColor: '#BB86FC',
  },
  barcodeIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#211630',
    alignItems: 'center',
    justifyContent: 'center',
  },
  barcodeTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  barcodeSubtitle: {
    color: '#999',
    fontSize: 11,
    marginTop: 4,
    lineHeight: 15,
  },
  scannerContainer: {
    flex: 1,
    backgroundColor: '#090909',
    padding: 20,
  },
  scannerSafeArea: {
    flex: 1,
    backgroundColor: '#090909',
  },
  scannerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
    paddingTop: 8,
  },
  scannerCloseBtn: {
    padding: 8,
    marginTop: 2,
  },
  scannerTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
  },
  scannerSubtitle: {
    color: '#888',
    fontSize: 13,
    marginTop: 6,
  },
  scannerViewport: {
    flex: 1,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#111',
    position: 'relative',
  },
  scannerCamera: {
    flex: 1,
  },
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  scannerFrame: {
    width: '76%',
    height: 170,
    borderWidth: 3,
    borderColor: '#BB86FC',
    borderRadius: 24,
    backgroundColor: 'transparent',
  },
  scannerFallback: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scannerFallbackText: {
    color: '#888',
    marginTop: 10,
  },
  scannerManualBtn: {
    marginTop: 20,
    backgroundColor: '#161621',
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  scannerManualBtnText: {
    color: '#BB86FC',
    fontWeight: '700',
  },
  scannerControls: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  scannerActionBtn: {
    flex: 1,
    backgroundColor: '#161621',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#2A2D41',
  },
  scannerActionBtnText: {
    color: '#BB86FC',
    fontWeight: '700',
    fontSize: 13,
  },
  scanHistorySection: {
    marginTop: 16,
  },
  scanHistoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  scanHistoryTitle: {
    color: '#999',
    fontSize: 12,
    fontWeight: '700',
  },
  scanHistoryClearText: {
    color: '#CF6679',
    fontSize: 12,
    fontWeight: '700',
  },
  scanHistoryRow: {
    gap: 10,
    paddingRight: 20,
  },
  scanHistoryChip: {
    width: 180,
    backgroundColor: '#161621',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#2A2D41',
  },
  scanHistoryChipLabel: {
    color: '#fff',
    fontWeight: '700',
  },
  scanHistoryChipMeta: {
    color: '#8B93B7',
    fontSize: 11,
    marginTop: 5,
  },
  recentSearchSection: {
    marginBottom: 15,
  },
  recentSearchTitle: {
    color: '#888',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  recentSearchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  recentSearchChip: {
    backgroundColor: '#1E1E1E',
    borderWidth: 1,
    borderColor: '#2F2F2F',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  recentSearchChipText: {
    color: '#BB86FC',
    fontWeight: '600',
  },
  discoverySection: {
    marginBottom: 16,
  },
  discoveryTitle: {
    color: '#888',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  discoveryChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  discoveryChip: {
    backgroundColor: '#1A1A1A',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  discoveryChipText: {
    color: '#D7D7D7',
    fontWeight: '600',
  },
  
  // Custom yemek butonu
  customMealBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E1E1E',
    padding: 12,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#BB86FC33',
    borderStyle: 'dashed',
  },
  customMealBtnText: {
    color: '#BB86FC',
    fontSize: 14,
    marginLeft: 8,
  },
  
  // Custom form
  customFormContainer: {
    flex: 1,
    paddingTop: 10,
  },
  customFormScroll: {
    flex: 1,
  },
  customFormScrollContent: {
    paddingBottom: 30,
  },
  customFormTitle: {
    color: '#BB86FC',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
  },
  customFormSubtitle: {
    color: '#888',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 20,
  },
  inputLabel: {
    color: '#888',
    fontSize: 12,
    marginBottom: 5,
    marginTop: 10,
  },
  customInput: {
    backgroundColor: '#1E1E1E',
    color: 'white',
    padding: 15,
    borderRadius: 12,
    fontSize: 16,
  },
  macroInputRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 5,
  },
  macroInputItem: {
    flex: 1,
  },
  calorieHint: {
    color: '#666',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 20,
    fontStyle: 'italic',
  },
  
  // Entry Type Selection
  entryTypeContainer: {
    flex: 1,
    paddingTop: 30,
  },
  entryTypeQuestion: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 30,
  },
  entryTypeBtn: {
    backgroundColor: '#1E1E1E',
    padding: 20,
    borderRadius: 16,
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },
  entryTypeBtnContent: {
    flex: 1,
    marginLeft: 15,
  },
  entryTypeBtnTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  entryTypeBtnDesc: {
    color: '#888',
    fontSize: 12,
  },
  quickPortionsCustom: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  quickBtnSmall: {
    backgroundColor: '#1E1E1E',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#333',
  },
  quickBtnSmallActive: {
    backgroundColor: '#BB86FC',
    borderColor: '#BB86FC',
  },
  quickBtnSmallText: {
    color: '#888',
    fontSize: 14,
  },
  quickBtnSmallTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  customPreviewCard: {
    backgroundColor: '#2A1D3D',
    padding: 15,
    borderRadius: 12,
    marginTop: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#BB86FC55',
  },
  customPreviewTitle: {
    color: '#BB86FC',
    fontSize: 12,
    marginBottom: 5,
  },
  customPreviewCalories: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
  },
  customPreviewPortion: {
    color: '#888',
    fontSize: 14,
    marginTop: 5,
  },
  
  // Result
  resultItem: {
    backgroundColor: '#1E1E1E',
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  resultName: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  resultBrand: { color: '#888', fontSize: 12 },
  resultBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  resultSourceBadge: {
    color: '#D5C7F6',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: '#2A1D3D',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  resultSourceBadgeVerified: {
    color: '#5EEAD4',
    backgroundColor: '#163433',
  },
  resultVerifiedBadge: {
    color: '#5EEAD4',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: '#163433',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  templateBadge: {
    color: '#FFD580',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: '#3A2A12',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  resultMacros: { color: '#666', fontSize: 12, marginTop: 5 },
  servingInfo: { color: '#BB86FC', fontSize: 11, marginTop: 3, opacity: 0.8 },
  favoriteBtn: {
    padding: 8,
    marginRight: 5,
  },
  
  // Empty favorites
  emptyFavorites: {
    alignItems: 'center',
    marginTop: 60,
    paddingHorizontal: 30,
  },
  emptyFavoritesText: {
    color: '#666',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 15,
  },
  emptyFavoritesSubtext: {
    color: '#444',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 10,
    lineHeight: 20,
  },
  searchEmptyState: {
    alignItems: 'center',
    marginTop: 50,
    paddingHorizontal: 30,
  },
  searchEmptyTitle: {
    color: '#888',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 14,
  },
  searchEmptyText: {
    color: '#555',
    textAlign: 'center',
    fontSize: 13,
    marginTop: 8,
    lineHeight: 19,
  },
  searchEmptyAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
    backgroundColor: '#1E1E1E',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BB86FC33',
  },
  searchEmptyActionText: {
    color: '#BB86FC',
    fontWeight: '700',
  },
  goalInputGroup: {
    marginBottom: 14,
  },
  goalInputLabel: {
    color: '#888',
    fontSize: 13,
    marginBottom: 6,
  },
  goalInput: {
    backgroundColor: '#1E1E1E',
    color: '#fff',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#333',
    fontSize: 16,
  },
  goalSaveBtn: {
    marginTop: 8,
    backgroundColor: '#BB86FC',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  goalSaveBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  
  // Miktar
  portionContainer: { flex: 1, alignItems: 'center', paddingTop: 20 },
  selectedName: { color: 'white', fontSize: 22, fontWeight: 'bold', textAlign: 'center' },
  selectedBadgeRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  selectedInfo: { color: '#888', fontSize: 14, marginTop: 5 },
  servingHint: { color: '#BB86FC', fontSize: 12, marginTop: 5, opacity: 0.8 },
  portionLabel: { color: '#BB86FC', fontSize: 14, marginTop: 30, marginBottom: 10 },
  portionInput: {
    backgroundColor: '#1E1E1E',
    color: 'white',
    padding: 15,
    borderRadius: 12,
    fontSize: 24,
    textAlign: 'center',
    width: 150,
  },
  quickPortions: { flexDirection: 'row', marginTop: 15, gap: 10, flexWrap: 'wrap', justifyContent: 'center' },
  quickBtn: {
    backgroundColor: '#333',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  servingBtn: {
    backgroundColor: '#2A1D3D',
    borderWidth: 1,
    borderColor: '#BB86FC',
  },
  quickBtnText: { color: '#BB86FC', fontWeight: 'bold' },
  quickBtnSubtext: { color: '#888', fontSize: 10, marginTop: 2 },
  
  previewCard: {
    backgroundColor: '#1E1E1E',
    padding: 20,
    borderRadius: 15,
    alignItems: 'center',
    marginTop: 30,
    width: '100%',
  },
  previewTitle: { color: '#888', fontSize: 12 },
  previewCalories: { color: '#BB86FC', fontSize: 36, fontWeight: 'bold' },
  previewMacros: { color: '#666', fontSize: 14, marginTop: 5 },
  
  buttonRow: { flexDirection: 'row', marginTop: 30, gap: 15, flexWrap: 'wrap', justifyContent: 'center' },
  secondaryActionBtn: {
    backgroundColor: '#1E1E1E',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BB86FC44',
  },
  secondaryActionBtnText: {
    color: '#BB86FC',
    fontWeight: 'bold',
  },
  backBtn: {
    backgroundColor: '#333',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 12,
  },
  backBtnText: { color: 'white', fontWeight: 'bold' },
  addBtn: {
    backgroundColor: '#BB86FC',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 12,
  },
  addBtnText: { color: 'white', fontWeight: 'bold' },
});
